// <auto-generated />
using HostingProcessEquipmentService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostingProcessEquipmentService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HostingProcessEquipmentService.Domain.Entities.EquipmentPlacementContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProcessEquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionFacilityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessEquipmentId");

                    b.HasIndex("ProductionFacilityId");

                    b.ToTable("EquipmentPlacementContracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentQuantity = 10,
                            ProcessEquipmentId = 1,
                            ProductionFacilityId = 1
                        },
                        new
                        {
                            Id = 2,
                            EquipmentQuantity = 5,
                            ProcessEquipmentId = 2,
                            ProductionFacilityId = 1
                        },
                        new
                        {
                            Id = 3,
                            EquipmentQuantity = 20,
                            ProcessEquipmentId = 3,
                            ProductionFacilityId = 2
                        },
                        new
                        {
                            Id = 4,
                            EquipmentQuantity = 8,
                            ProcessEquipmentId = 1,
                            ProductionFacilityId = 3
                        },
                        new
                        {
                            Id = 5,
                            EquipmentQuantity = 12,
                            ProcessEquipmentId = 2,
                            ProductionFacilityId = 3
                        });
                });

            modelBuilder.Entity("HostingProcessEquipmentService.Domain.Entities.ProcessEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProcessEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 25.0,
                            Code = "PE001",
                            Name = "Обладнання 1"
                        },
                        new
                        {
                            Id = 2,
                            Area = 30.5,
                            Code = "PE002",
                            Name = "Обладнання 2"
                        },
                        new
                        {
                            Id = 3,
                            Area = 15.0,
                            Code = "PE003",
                            Name = "Обладнання 3"
                        });
                });

            modelBuilder.Entity("HostingProcessEquipmentService.Domain.Entities.ProductionFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StandardArea")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductionFacilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PF001",
                            Name = "Завод 1",
                            StandardArea = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "PF002",
                            Name = "Завод 2",
                            StandardArea = 1500.0
                        },
                        new
                        {
                            Id = 3,
                            Code = "PF003",
                            Name = "Завод 3",
                            StandardArea = 2000.0
                        });
                });

            modelBuilder.Entity("HostingProcessEquipmentService.Domain.Entities.EquipmentPlacementContract", b =>
                {
                    b.HasOne("HostingProcessEquipmentService.Domain.Entities.ProcessEquipment", "ProcessEquipment")
                        .WithMany()
                        .HasForeignKey("ProcessEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HostingProcessEquipmentService.Domain.Entities.ProductionFacility", "ProductionFacility")
                        .WithMany("Contracts")
                        .HasForeignKey("ProductionFacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessEquipment");

                    b.Navigation("ProductionFacility");
                });

            modelBuilder.Entity("HostingProcessEquipmentService.Domain.Entities.ProductionFacility", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
